# Generated by Django 5.1.2 on 2024-10-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0002_remove_tareas_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listas',
            name='tablero',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='lista',
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha_fin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Tableros',
        ),
        migrations.DeleteModel(
            name='Listas',
        ),
    ]
