# Generated by Django 5.1.2 on 2024-10-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0003_remove_listas_tablero_remove_tareas_lista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
    ]
